### ISSUE TITLE
hi my friend, where is your code?

### ISSUE THREAD

**Issue by daima2017** [Immortals88/Demo-SEA#1]
hi my friend, where is your code?

**Comment by Immortals88** [comment]
I'm quite sorry my friend, there are some small issues on the front end of GUI, but I have no time to fix them this year. If your are interested in this project, you can refer to https://github.com/xz-liu/ClusterEA, which is the backbone of SEA.  The owner of that repo is an expert on EA, who is also my colleague.  I'll upload the code in early 2024 as soon as possible. Thanks for your interest and patience.
